function [p] = material_kinetics(T,mat)
switch mat
    case('U235')
        nu_Sigma_f  = 30;
        p.lambda_k    = [0.0124;...
            0.0305;...
            0.111;...
            0.301;...
            1.14;...
            3.01];
        p.beta    = 0.00650;
        p.beta_k  = [0.033;...
            0.219;...
            0.196;...
            0.395;...
            0.115;...
            0.042]*p.beta;
    otherwise
        disp('Error - Unknown Material')
end
[v_ave v_inv]   = average_vel(T);
p.Lambda        = 1/(v_ave*nu_Sigma_f);
p.lambda.ave    = sum(p.lambda_k.*p.beta_k)/p.beta;
p.lambda.inv    = p.beta/sum(p.beta_k./p.lambda_k);
p.lambda1G      = p.lambda.inv;
end